### ISSUE TITLE
Don't redefine terminology

### ISSUE THREAD

**Issue by WhyNotHugo** [bitfireAT/webdav-push#45]
The `Terminology` section defines a few terms which are already defined in RFC8030 (the specification for **HTTP Web Push**): https://datatracker.ietf.org/doc/html/rfc8030#section-1.1

For example, RFC8030 reads:

>    push message:  A message sent from an application server to a user
>       agent via a push service.

And the current draft defines the same concept in other words:

>    Push message  Actual network message that is sent from the server
>       over a push transport to the client.  Notifies the client that a
>       specific collection (identified by its push topic) has changed.

Instead, the draft should re-use existing terminology:

> This specification reuses much of the same terminology as RFC8030

**Comment by rfc2822** [comment]
Since Web Push is only _a_ (although the only at the moment) transport, I think we need to do that
