### ISSUE TITLE
                    Message Encryption for Web Push

### ISSUE THREAD

**Issue by WhyNotHugo** [bitfireAT/webdav-push#47]
I believe that [Message Encryption for Web Push (rfc8291)](https://datatracker.ietf.org/doc/html/rfc8291) should satisfy the confidentiality requirements for this extension.

**Comment by rfc2822** [comment]
Thanks for all your suggestions, I'll have a look and answer on the next iteration (may take a while).

Regarding message encryption: it's already mentioned, for instance here: https://bitfireat.github.io/webdav-push/draft-bitfire-webdav-push-00.html#name-message-encryption

Do you have a specific suggestions regarding it?

**Comment by rfc2822** [comment]
Described in https://bitfireat.github.io/webdav-push/draft-bitfire-webdav-push-00.html#name-message-encryption, please create a new discussion if there's a specific sub-topic

**Comment by WhyNotHugo** [comment]
Nice! I think that simply delegating to an existing RFC like this is great.
